<?php $__env->startSection('body'); ?>
   <div class="banner1">
			<div class="container">
				<h3><a href="index.html">Home</a> / <span>Cart Products</span></h3>
			</div>
    </div>
	<!--banner-->

	<!--content-->
		<div class="content">
			<!--single-->
			<div class="single-wl3">
				<div class="container">
          <div class="row">
            <div class="col-md-11 col-md-offset-1">
              <h3 class="text-center text-success">My Shopping Cart</h3>
              <hr />
              <table class="table table-bordered">

                <tr class="bg-primary">
                  <th>SL NO.</th>
                  <th>Name</th>
                  <th>Image</th>
                  <th>Price</th>
                  <th>Quantity</th>
                  <th>Total Price</th>
                  <th>Action</th>
                </tr>
                <?php ($i=1); ?>
                <?php ($sum=0); ?>
                <?php $__currentLoopData = $cartProducts; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $cartProduct): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                <tr>
                  <td><?php echo e($i++); ?></td>
                  <td><?php echo e($cartProduct->name); ?></td>
                  <td><img src="<?php echo e(asset($cartProduct->options->image)); ?>" alt=""/></td>
                  <td><?php echo e($cartProduct->price); ?></td>
                  <td>
                    <?php echo e(Form::open(['route'=>'update-cart','method'=>'post'])); ?>

                      <input type="number" name="qty" value="<?php echo e($cartProduct->qty); ?>" min="1" />
                      <input type="hidden" name="rowId" value="<?php echo e($cartProduct->rowId); ?>" />
                      <input type="submit" name="btn" value="Update"/>
                    <?php echo e(Form::close()); ?>

                  </td>
                  <td>.BDT <?php echo e($total=$cartProduct->price * $cartProduct->qty); ?></td>
                  <td>
                    <a href="<?php echo e(route('delete-cart-item',['rowId'=>$cartProduct->rowId])); ?>" class="btn btn-danger btn-xs" title="Remove">
                        <span class="glyphicon glyphicon-trash"></span><!--rowId is in $cartProduct generated by Cart class-->
                    </a>
                  </td>
                </tr>
                <?php $sum= $sum+$total;?>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
              </table>
              <table class="table table-bordered">
                <tr>
                  <th>Net Items Price Total </th>
                  <td>BDT. <?php echo e($sum); ?></td>
                </tr>
                <tr>
                  <th>Vat </th>
                  <td>BDT. <?php echo e($vat=0); ?></td>
                </tr>
                <tr>
                  <th>Grand Total </th>
                  <td>BDT. <?php echo e($orderTotal= $sum+$vat); ?></td>
                  <?php Session::put('orderTotal', $orderTotal)?>
                </tr>
              </table>
            </div>
          </div>
          <div class="row">
            <div class="col-md-11 col-md-offset-1">
              <?php if(Session::get('customerId') && Session::get('shippingId')): ?>
                <a href="<?php echo e(route('checkout-payment')); ?>" class="btn btn-warning pull-right">Checkout</a>
              <?php elseif(Session::get('customerId')): ?>
                <a href="<?php echo e(route('checkout-shipping')); ?>" class="btn btn-warning pull-right">Checkout</a>
              <?php else: ?>
                <a href="<?php echo e(route('checkout')); ?>" class="btn btn-warning pull-right">Login/Signin Next</a>
              <?php endif; ?>
                <a href="<?php echo e(route('/')); ?>" class="btn btn-success ">Shop More</a>
            </div>
          </div>

				</div>
			</div>
			<!--single-->

			<!--new-arrivals-->
		</div>


<?php $__env->stopSection(); ?>

<?php echo $__env->make('front-end.master', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\xampp\htdocs\FirstProject\resources\views/front-end/cart/show-cart.blade.php ENDPATH**/ ?>