
@extends('front-end.master')
@section('body')
   <div class="banner1">
			<div class="container">
				<h3><a href="index.html">Home</a> / <span>Cart Products</span></h3>
			</div>
    </div>
	<!--banner-->

	<!--content-->
		<div class="content">
			<!--single-->
			<div class="single-wl3">
				<div class="container">
          <div class="row">
            <div class="col-md-11 col-md-offset-1">
              <h3 class="text-center text-success">My Shopping Cart</h3>
              <hr />
              <table class="table table-bordered">

                <tr class="bg-primary">
                  <th>SL NO.</th>
                  <th>Name</th>
                  <th>Image</th>
                  <th>Price</th>
                  <th>Quantity</th>
                  <th>Total Price</th>
                  <th>Action</th>
                </tr>
                @php($i=1)
                @php($sum=0)
                @foreach($cartProducts as $cartProduct)
                <tr>
                  <td>{{$i++}}</td>
                  <td>{{$cartProduct->name}}</td>
                  <td><img src="{{asset($cartProduct->options->image)}}" alt=""/></td>
                  <td>{{$cartProduct->price}}</td>
                  <td>
                    {{ Form::open(['route'=>'update-cart','method'=>'post']) }}
                      <input type="number" name="qty" value="{{$cartProduct->qty}}" min="1" />
                      <input type="hidden" name="rowId" value="{{$cartProduct->rowId}}" />
                      <input type="submit" name="btn" value="Update"/>
                    {{Form::close()}}
                  </td>
                  <td>.BDT {{$total=$cartProduct->price * $cartProduct->qty}}</td>
                  <td>
                    <a href="{{route('delete-cart-item',['rowId'=>$cartProduct->rowId])}}" class="btn btn-danger btn-xs" title="Remove">
                        <span class="glyphicon glyphicon-trash"></span><!--rowId is in $cartProduct generated by Cart class-->
                    </a>
                  </td>
                </tr>
                <?php $sum= $sum+$total;?>
                @endforeach
              </table>
              <table class="table table-bordered">
                <tr>
                  <th>Net Items Price Total </th>
                  <td>BDT. {{$sum}}</td>
                </tr>
                <tr>
                  <th>Vat </th>
                  <td>BDT. {{$vat=0}}</td>
                </tr>
                <tr>
                  <th>Grand Total </th>
                  <td>BDT. {{$orderTotal= $sum+$vat}}</td>
                  <?php Session::put('orderTotal', $orderTotal)?>
                </tr>
              </table>
            </div>
          </div>
          <div class="row">
            <div class="col-md-11 col-md-offset-1">
              @if(Session::get('customerId') && Session::get('shippingId'))
                <a href="{{ route('checkout-payment') }}" class="btn btn-warning pull-right">Checkout</a>
              @elseif(Session::get('customerId'))
                <a href="{{ route('checkout-shipping') }}" class="btn btn-warning pull-right">Checkout</a>
              @else
                <a href="{{ route('checkout') }}" class="btn btn-warning pull-right">Login/Signin Next</a>
              @endif
                <a href="{{ route('/') }}" class="btn btn-success ">Shop More</a>
            </div>
          </div>

				</div>
			</div>
			<!--single-->

			<!--new-arrivals-->
		</div>


@endsection
